### 1. Buatlah variabel dengan nama ClubEropa dengan tipe data dictionary 4 key (nama_club, pelatih_club, Negara, pemain), yang masing-masing nya memiliki 4 value Bebas

In [ ]:
ClubEropa = {
    "nama_club": "Barcelonar",
    "pelatih_club": "Ronald Koeman", 
    "Negara": "Spanish", 
    "pemain": "Gerard Pique",
}
print(ClubEropa)

{'nama_club': 'Barcelonar', 'pelatih_club': 'Ronald Koeman', 'Negara': 'Spanish', 'pemain': 'Gerard Pique'}


### 2. Tambahkan key sponsor pada variabel ClubEropa yang tentunya memiliki 4 value.

In [ ]:
ClubEropa["sponsor"] = "adidas"
print(ClubEropa)

{'nama_club': 'Barcelonar', 'pelatih_club': 'Ronald Koeman', 'Negara': 'Spanish', 'pemain': 'Gerard Pique', 'sponsor': 'adidas'}


### 3. Buatlah 4 variable array yang memiliki 5 elemen angka pada masing-masing nya (bebas nama array dan elemennya), kemudian lakukan:          

In [ ]:
import numpy as np
array_1 = np.array([5,8,12,32,6])
array_2 = np.array([43,76,53,90,52])
array_3 = np.array([12,54,2,7,34])
array_4 = np.array([1,2,3,4,5])

a. Perkalian pada variable array 1 dengan variable array 3

In [ ]:
perkalian = np.multiply(array_1, array_3)
print(perkalian)

[ 60 432  24 224 204]


b. Penjumlahan pada variable array 2 dengan variable array 4

In [ ]:
penjumlahan = np.add(array_2, array_4)
print(penjumlahan)

[44 78 56 94 57]


c. Jika ada irisan, dapatkan irisan pada variable 1 dengan 4

In [ ]:
irisan = np.intersect1d(array_1, array_4, assume_unique=True)
print(irisan)

[5]


d. Ambil nilai pada urutan ke 1, 3, dan 5 pada variabel kedua

In [ ]:
ind = [0,2,4]
array_2[ind]

array([43, 53, 52])

### 4. Buatlah variabel nilai_kelas dari 4 kelas berbeda, dimana masing masing kelas berisi nilai 4 siswa, kemudian kurangi semua nilai siswa dengan 5 sebagai nilai hukuman karena menyontek

In [ ]:
nilai_kelas = np.array([[100,80,75,85], [80,80,95,65], [80,90,95,70], [90,97,86,79]])
hukuman = np.array([5])
nilai_final = np.subtract(nilai_kelas, hukuman)
print(nilai_final)

[[95 75 70 80]
 [75 75 90 60]
 [75 85 90 65]
 [85 92 81 74]]


### 5. jelaskan sejarah python, keunggulan dan apa kegunaannya?

**Sejarah**

Python diciptakan oleh Guido van Rossum pertama kali di  Centrum Wiskunde & Informatica (CWI) di Belanda pada awal tahun 1990-an. Di tahun 1995, Guido melanjutkan pembuatan python di Corporation for National Research Initiative (CNRI) di Virginia Amerika, di mana dia merilis beberapa versi dari python. Pada Mei 2000, Guido dan tim Python pindah ke BeOpen.com dan membentuk tim BeOpen PythonLabs. Di bulan Oktober pada tahun yang sama, tim python pindah ke Digital Creation (sekarang menjadi Perusahaan Zope). Pada tahun 2001, dibentuklah Organisasi Python yaitu Python Software Foundation (PSF). PSF merupakan organisasi nirlaba yang dibuat khusus untuk semua hal yang berkaitan dengan hak intelektual Python.

Semua versi python yang dirilis bersifat open source. Dalam sejarahnya, hampir semua rilis python menggunakan lisensi GFL-compatible.

Nama python sendiri tidak berasal dari nama ular yang kita kenal. Guido adalah penggemar grup komedi Inggris bernama Monty Python. Ia kemudian menamai bahasa ciptaannya dengan nama Python.


---

**Keunggulan **

Python merupakan bahasa pemrograman yang dianggap mudah untuk dipelajari, selain itu python memiliki kemudahannya dalam diaplikasikan dalam mengembangkan sebuah produk, baik itu web, software, maupun video game. kemudian Program yang ditulis menggunakan Python dapat dijalankan di hampir semua sistem operasi dan open source.


---

**Kegunaan**

Python dapat diaplikasikan dalam mengembangkan sebuah produk baik itu web, software, Analisis data dan video game. selain itu python juga mendukung ekosistem IoT. 
